# -*- coding: utf-8 -*-
"""hotel booking Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cb6r5pVVVV_Q4njRj-JYFnQ5rxiI6bf_

# **Project Name**    -

##### **Project Type**    - Hotel Booking Analysis
##### **Contribution**    - Individual

# **Project Summary -**

This EDA project on Hotel Booking Analysis investigates cancellations, and their underlying patterns; and suggests measures that can be implemented to reduce cancellations and secure revenue1:

The project covers booking information for a city hotel and a resort hotel including information such as when the booking was made, length of stay, the number of adults, children. The project went through the basic idea of the EDA and visualization process.

In this project I will do Exploratory Data Analysis on the given dataset. The project suggests measures that can be implemented to reduce cancellations and secure revenue. For example, hotels can offer discounts or promotions to customers who book early or who book for longer stays. Hotels can also offer incentives such as free parking or free breakfast to customers who book directly with them instead of through third-party websites.

This EDA involves following steps where in first step involves exploration and inspection over raw data, and second in second step I have dealt with data impurities and cleaned the data by andling null values and dropping irrelevent data from the dataset.

This EDA is divided into following 3 analysis: Univariate analysis: Univariate analysis is the simplest of the three analyses where the data, you are analyzing is only one variable. Bivariate analysis: Bivariate analysis is where you are comparing two variables to study their relationships. Multivariate analysis: Multivariate analysis is similar to Bivariate analysis but you are comparing more than two variables.

The project concludes that by analyzing hotel bookings data and understanding cancellations patterns, hotels can take steps to reduce cancellations and increase revenue.

# **GitHub Link -**

https://github.com/abhishekjadon1/hotel-booking-analysis/blob/main/hotel_booking_Analysis.ipynb

# **Problem Statement**

Have you ever wondered when the best time of year to book a hotel room is? Or the optimal length of stay in order to get the best daily rate? What if you wanted to predict whether or not a hotel was likely to receive a disproportionately high number of special requests? This hotel booking dataset can help you explore those questions! This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things. All personally Identifying information has been removed from the data..

#### **Define Your Business Objective?**

The project aims to gain interesting insight into customers' behavior when booking a hotel. The demand for different segment of customer may differ and forecasting become harder as it may requires different model for different segment. These insights can guide hotels to adjust their customer strategies and make preparation for unknown

# ***Let's Begin !***

1. Know Your Data

### Import Libraries
"""

# Importing neccessay Libraries needed in EDA
import numpy as pd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""### Dataset Loading"""

from google.colab import drive
drive.mount('/content/drive')

from os import path
path  = '/content/drive/MyDrive/data/Hotel Bookings (1).xlsx'
df = pd.read_excel(path)

"""### Dataset First View"""

# Dataset First Look
df.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
df.shape

"""### Dataset Information"""

# Dataset Info
df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
len(df[df.duplicated()])

"""There are 31994 duplicate values"""

df.drop_duplicates(inplace=True)

df.shape

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
print(df.isnull().sum())

# Visualizing the missing values
# checking Null Value by plotting heatmap
plt.figure(figsize=(20,8))
sns.heatmap(df.isnull(),yticklabels=False,cbar=False,cmap='viridis')
cmap="YlGnBu",
cbar_kws={'label': 'Missing Data'}
plt.title('Missing values',fontsize=18)
plt.show

"""### What did you know about your dataset?

We can see that there are total four columns with missing/null values: company, agent, country, children.

1. In children column, I will replace null values with 0 assuming that customer did not have any children.

2. Column country has null values. I will reolace null values in this column with 'Others' assuming customer's country was not mentioned while booking.

3. In company and agent column it might be a case when customers did not book hotel through them so these columns might have null values in it. As these 2 columns have numeric data in it, I will replace them with 0.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df.columns

# Dataset Describe
df.describe()

"""### Variables Description

Hotel: (Resort Hotel or City Hotel)

is_canceled: Value indicating if the booking was canceled (1) or not (0)

lead_time: * Number of days that elapsed between the entering date of the booking into the PMS and the arrival date*

arrival_date_year: Year of arrival date

arrival_date_month: Month of arrival date

arrival_date_week_number: Week number of year for arrival date

arrival_date_day_of_month: Day of arrival date

stays_in_weekend_nights: Number of weekend nights (Saturday or Sunday) the guest stayed or booked to stay at the hotel

stays_in_week_nights: Number of week nights (Monday to Friday) the guest stayed or booked to stay at the hotel

adults: Number of adults

children: Number of children

babies: Number of babies

meal: Type of meal booked. Categories are presented in standard hospitality meal packages

country: Country of origin. market_segment: Market segment designation. In categories, the term "TA" means "Travel Agents" and "TO" means
"Tour Operators

distribution_channel: Booking distribution channel. The term "TA" means "Travel Agents" and "TO" means "Tour Operators"

is_repeated_guest: Value indicating if the booking name was from a repeated guest (1) or not (0)

previous_cancellations: Number of previous bookings that were cancelled by the customer prior to the current booking

previous_bookings_not_canceled: Number of previous bookings not cancelled by the customer prior to the current booking

reserved_room_type: Code of room type reserved. Code is presented instead of designation for anonymity reasons.

assigned_room_type: Code for the type of room assigned to the booking.

booking_changes: Number of changes/amendments made to the booking from the moment the booking was entered on the PMS until the moment of check-in or cancellation

deposit_type: Indication on if the customer made a deposit to guarantee the booking.

agent: ID of the travel agency that made the booking

company: ID of the company/entity that made the booking or responsible for paying the booking.

days_in_waiting_list: Number of days the booking was in the waiting list before it was confirmed to the customer

customer_type: Type of booking, assuming one of four categories

adr: Average Daily Rate as defined by dividing the sum of all lodging transactions by the total number of staying nights

required_car_parking_spaces: Number of car parking spaces required by the customer

total_of_special_requests: Number of special requests made by the customer (e.g. twin bed or high floor)

reservation_status: Reservation last status, assuming one of three categories

Canceled - booking was canceled by the customer Check-Out - customer has checked in but already departed No-Show - customer did not

check-in and did inform the hotel of the reason why reservation_status_date - Date at which the last status was set

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
pd.Series(df.nunique()).sort_values(ascending=False)

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.
df1 = df.copy()

df1.columns

# replacing null values in  children column with 0 assuming that family had 0 children
# replacing null values in company and agent column with 0 assuming those rooms were booked without company/agent
df1['children'].fillna(0,inplace=True)
df1['company'].fillna(0,inplace=True)
df1['agent'].fillna(0,inplace=True)
# replacing null values in country column as'Other'
df1['country'].fillna('Others',inplace=True)

# checking for null values after replacing them
df1.isnull().sum()

# dropping the 'company' column as it contain a lot of null values in coparison to other columns
df1.drop(['company'],axis=1,inplace=True) #dropping the values vertically at axis 1 (columns)

#dropping rows where no adults , children and babies are available because no bookings were made that day
no_guest = df1[(df1['adults']==0) & (df1['children']==0) & (df1['babies']==0)]
df1.drop(no_guest.index,inplace=True)

# adding some new columns to make our data analysis ready
df1['total_stay'] = df1['stays_in_weekend_nights'] + df1['stays_in_week_nights'] # total nights spent by guest
df1['total_people'] = df1['adults'] + df1['children'] + df1['babies'] # creating a column to heck total stay by people in that booking

# having a final look to check if our dataset is ready to analyse
df1.head()

df1.tail()

# checking the final shape of the dataset
print(f' final shape of the dataset is {df1.shape}')

"""### What all manipulations have you done and insights you found?

Created a copy of the dataset before doing any manipulation then filled missing values with 0 in children, company and agent columns as those columns had numerical values and in column country filled missing values with 'others'. after dealing with missing values I dropped the country column as this had 96% missing values and was of no use in our analysis. In next step I created 2 new columns named 'total_people' and 'total_stay' for further analysis. In total people column I added all the babies, children and adults. similarly in second new column I added weekend stay and week stay column.

After doing all the manipulation I checked new manipulated dataset to check if this is ready to be analyzed.

After manipulating the dataset these were the insights I found:

1. There are 2 types of hotel which guests could book so I can find which type of hotel was booked most.

2. There are different types of guests and they come from different countries.

3. Guests can choose different foods from the menu.

4. Guests can book hotel directly or through different channels that are available.

5. Guests can cancel their booking and there are repeated guests also.

6. Guests can choose rooms of their liking while booking.

7. There is column available in the dataset named 'adr' which could be used to analyze hotel's performance on the basis of revenue.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1

Which type of hotel is most prefferd by the guests?
"""

# Chart - 1 visualization code
# string unique hotel names in a variable
hotel_names = df1['hotel'].unique()

#checking the number of unique booking in each hotel type
hotel_booking = df1['hotel'].value_counts()

# creating a donut chart using plotly.express
fig1 = px.pie(hotel_booking, values=hotel_booking.values, names=hotel_booking.index, hole=0.5, title='Hotel Booking Percentage')

# updating the appearance of the chart
fig1.update_traces(textposition='outside', textinfo='percent+label')
fig1 .update_layout(legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='center', x=0.5))

"""Creating a Pie chart also for the above problem statement as Donut chart is not exported to github"""

# count Hotel
hotel_booking = df1['hotel'].value_counts()
# plot
plt.figure(figsize=(10,7))
plt.pie(hotel_booking, labels=hotel_booking.index, autopct='%1.1f%%')
plt.title('Hotel Booking Percentage')

"""##### 1. Why did you pick the specific chart?

I used Donut chart here because it is used to show the proportions of categorical data, with the size of each piece representing the proportion of each category.

##### 2. What is/are the insight(s) found from the chart?

I found out that guests prefer Resort Hotel most over City Hotel.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight is useful for the stakeholder to check which hotel is performing best and they can invest more capitals in that. There is no such negative growth but stakeholders can focus more on City Hotel to get more booking and icrease the overall revenue.

#### Chart - 2

Which is percentage of hotel booking cancellation?
"""

# Chart - 2 visualization code
# Extrcting and storing unique values of hotel cancelation
cancelation = df1.is_canceled.value_counts()

#creating a pie chart
cancelation.plot.pie(explode=[0.05,0.05], autopct='%1.2f%%', shadow=True, figsize=(9,8),fontsize=15)

#adding title
plt.title('Percentage of Cancelation')

"""##### 1. Why did you pick the specific chart?

I had to show a part-to-a-whole relationship and percentage of both the values and here pie chart was a good option to show segmented values.

##### 2. What is/are the insight(s) found from the chart?

Here we can see that around 72.48% bookins are not canceled by guests but around 27.52% bookings are canceled by guests

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

This insight will help stakeholders in comparing the cancellation and non cancellation of bookings. With the help of this insight stakeholders can offer rescheduling the bookings instead of cancellation and set a flexible cancellation policy to reduce booking cancellation.

#### Chart - 3

Which type of meal is most preffered by guests?
"""

# Chart - 3 visualization code
# Counting each meal type
meal_type = df1['meal'].value_counts()

# Exracting each meal type and storing in a variable
meal_name = df1['meal'].unique()

# Creating a dataset of each meal type and count
meal_df = pd.DataFrame({'meal':meal_name,'count':meal_type})

# Visualising the values on a bar chart
plt.figure(figsize=(10,7))
sns.barplot(x='meal',y='count',data=meal_df)
plt.title('Most preffred meal Type', fontsize = 25)
plt.xlabel('Meal Type', fontsize = 15)
plt.ylabel('Count', fontsize = 15)

"""Meal type variable description:

BB - (Bed and Breakfast)

HB- (Half Board)

FB- (Full Board)

SC- (Self Catering)

##### 1. Why did you pick the specific chart?

There were 4 values to compare and Bar graphs are used to compare things between different groups that is why I used this chart.

##### 2. What is/are the insight(s) found from the chart?

After visualizing the above chart we can see that BB - (Bed and Breakfast) is the most preffered meal type by guests.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, from the gained insight above now stakeholders know that BB(Bed and Breakfast) is most preferred meal type so they can arrange raw material for this meal in advance and deliver the meal without any delay.

#### Chart - 4

Which year has the most bookings ?
"""

# Chart - 4 visualization code
# Plotting with countplot
plt.figure(figsize=(10,7))
sns.countplot(x=df1 ['arrival_date_year'], hue=df1['hotel'])
plt.title('Number of bookings across year', fontsize = 25)
plt.xlabel('Year', fontsize = 15)

"""##### 1. Why did you pick the specific chart?

Bar graphs are used to compare things between different groups that is why I used this chart.

##### 2. What is/are the insight(s) found from the chart?

From above insight I found out that hotel was booked most times in year 2016

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Above insight shows that number of booking was declined after year 2016. Stakeholders can now what went wrong after 2016 and fix that problem to increase the umber of bookings. One way to do this is ask for feedbacks from guests and have a meeting with old employees who else were serving int the year 2016.

#### Chart - 5

Which month has the most booking in each hotel type?
"""

# Chart - 5 visualization code
plt.figure(figsize=(15,5))
sns.countplot(x=df1 ['arrival_date_month'], hue=df1['hotel'])
plt.title('Number of bookings across month', fontsize = 25)
plt.xlabel('Month', fontsize = 15)

"""##### 1. Why did you pick the specific chart?

I had to compare values across the months and for that bar chart was one of the best choice.

##### 2. What is/are the insight(s) found from the chart?

Above insight shows that August and July ware 2 most busy months in compare to others.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

There is negative insight but hotel can use this insight to arrange everything in advance and welcome their guest in the best way possible and hotel can also run some promotional offer in these 2 months to attract more guests.

#### Chart - 6

How long people stay in the hotel?
"""

# Chart - 6 visualization code
# Creating a not cancelled dataframe
not_canceled = df1[df1['is_canceled'] == 0]

# Creating a dataframe of total stay
total_stay = not_canceled['total_stay']

# setting plot size and plotting barchart
plt.figure(figsize=(15,5))
sns.countplot(x=total_stay, hue=df1['hotel'])
plt.title('Total number of stay in each hotel', fontsize = 25)
plt.xlabel('Total Stay', fontsize = 15)
plt.ylabel('Count', fontsize = 15)

"""From the above chart we can see that in City hotel most people stay for 3 days and in Resort hotel  most people stay for only 1 day. Hotel should work on to increase total stay in Resort hotel to increase revenue.

#### Chart - 7

Which distribution channel is most used in booking
"""

# Chart - 7 visualization code
# creating a dataset of distribution channel name and count
dist_df = df1['distribution_channel'].value_counts().reset_index()

#renaming the columns to approproiate names
dist_df.columns=['distribution_channel','count']

#creating a explode data
my_explode = [0.05,0.05,0.05,0.05,0.05]

# adding percentage columns to the distribution_channel_df
dist_df['percentage'] = (dist_df['count']/dist_df['count'].sum())*50

#decinding the figure size
plt.figure(figsize=(15,5))

#plotting the chart value
plt.pie(dist_df['count'],labels=dist_df['distribution_channel'],explode=my_explode,startangle = 50)

# adding legends with percentage using list comprehension
labels = [f'{label} ({percent:.1f}%)' for label, percent in zip(dist_df['distribution_channel'], dist_df['percentage'])]

plt.legend(labels, loc='upper right')

# setting the chart title
plt.title('Distribution Channel')

#show the chart
plt.axis('equal')
plt.show()

"""##### 1. Why did you pick the specific chart?

Pie chart is one of the best chart to visualize categoriacal data.

##### 2. What is/are the insight(s) found from the chart?

From the above insight it is clear that TA/TO (travel agents/pur operators) is most used distribution channel by guests.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

There is no negative insight. Hotels can run promotional offers to motivate other channels to contribute more in bookings.

#### Chart - 8

Which room type is most preffered by guests?
"""

# Chart - 8 visualization code
# setting the figure size
plt.figure(figsize=(15,5))

# plotting the chart
sns.countplot(x=df1['reserved_room_type'],order=df1['reserved_room_type'].value_counts().index)

# setting the chart title
plt.title('Preffered Room Type by guest')

# show the chart
plt.show()

"""##### 1. Why did you pick the specific chart?

A bar plot shows catergorical data as rectangular bars with the height of bars proportional to the value they represent. It is often used to compare between values of different categories in the data.

##### 2. What is/are the insight(s) found from the chart?

By observing the above chart we can understand that the room type A most preffered (almost 55,000) by the guests while booking the hotel

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

As it is clear that room type A is most used hotel should increase the number of A type room to maximize the revenue.

#### Chart - 9

Which room type is most assigned?
"""

# Chart - 9 visualization code
# Setting the figure size
plt.figure(figsize=(15,5))

# Plotting the values
sns.countplot(x=df1['assigned_room_type'],order=df1['assigned_room_type'].value_counts().index)

#setting the title
plt.title('Assigned Room Type')

#show the chart
plt.show()

"""##### 1. Why did you pick the specific chart?

A bar plot shows catergorical data as rectangular bars with the height of bars proportional to the value they represent.

##### 2. What is/are the insight(s) found from the chart?

From the above chart it is clear that room type A is most assigned to guests.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

In the 8th chart we saw that around 55,000 guests preffered room type A but 45,000 people were assigned A type room. This could be a reason to cancel the bookings. Hotel could increase A type room to decrease cancellation.

#### Chart - 10

What is the percentage of repeated guests?
"""

# chart 10 visualization code
# creating a variable containing guests with their repeated counts
rep_guest = df1['is_repeated_guest'].value_counts()

# plotting the values in the pie chart
rep_guest.plot.pie(explode=[0.05,0.09], autopct='%1.2f%%', shadow=True, figsize=(15,6),fontsize=15)

# setting the title
plt.title('Percentage of Repeated Guests',fontsize=20)

#setting the chart in centre
plt.axis('equal')

#show the chart
plt.show()

"""##### 1. Why did you pick the specific chart?

A pie chart helps organize and show data as a percentage of a whole

##### 2. What is/are the insight(s) found from the chart?

From the above insight we can see that 3.86% guests are repeated guests

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

We can see that number of repeated guests is very low and it shows negative growth of the hotel. Hotel can offer loyality discount to their guests to increase repeated guests.

#### Chart - 11

Which customer type has the most booking?
"""

# Chart - 11 visualization code
# creating a variable containing customer type with their counts
cust_type = df1['customer_type'].value_counts()

# plotting the values in the line chart
cust_type.plot(figsize=(15,5))

#setting the x label , y label and title
plt.xlabel('Customer Type')
plt.ylabel('Count')
plt.title('Customer Type')

#show the chart
plt.show()

"""##### 1. Why did you pick the specific chart?

Line graphs are used to track changes over different categories.

##### 2. What is/are the insight(s) found from the chart?

We can see that Transient customer type has most number of bookings.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Hotel can run promotional offers to increase the number of bookings over other categories, such as hotel could offer discounts for groups.

#### Chart - 12

Which market segment has the most booking?
"""

# Chart - 12 visualization code
plt.figure(figsize=(15,5))
sns.countplot(x=df1['market_segment'],order=df1['market_segment'].value_counts().index)
plt.title('Market Segment')
plt.show()

"""##### 1. Why did you pick the specific chart?

A bar plot shows catergorical data as rectangular bars with the height of bars proportional to the value they represent.

##### 2. What is/are the insight(s) found from the chart?

Above insight shows that Online TA (Travel Agent) has the most bookings.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

There is no negative growth. Hotel should come up with some great idea to increase sahre among other market segments to increase the revenue.

#### Chart - 13

Which deposite type is most preffered?
"""

# Chart - 13 visualization code
# counting each deposite type
deposite = df1['deposit_type'].value_counts().index


# setting the chart size
plt.figure(figsize=(8,4))

# plotting the values
sns.countplot(x=df1['deposit_type'],order=deposite)

# setting the title
plt.title('Deposite Type')

# show the chart
plt.show()

"""Bivariate and multivariate analysis

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code
# Setting the chart size
plt.figure(figsize=(15,10))

# Creating heatmap to see correlation of each columns
sns.heatmap(df1.corr(numeric_only=True),annot=True)     #Setting the numeric only columns to true to avoid warning

# setting the title
plt.title('Correlation of the columns', fontsize=20)

# show heatmap
plt.show()

"""##### 1. Why did you pick the specific chart?

Correlation heatmaps was used to find potential relationships between variables and to understand the strength of these relationships.

##### 2. What is/are the insight(s) found from the chart?

1) lead_time and total_stay is positively corelated. that means if customers stay more then the lead time increases.

2)adults, childrens and babies are corelated to each other. That means more the people more will be adr.

3) is_repeated guest and previous bookings not canceled has strong corelation. That means repeated guests don't cancel their bookings.**

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code
sns.pairplot(df1)
plt.show()

"""##### 1. Why did you pick the specific chart?

A pairs plot allows us to see both distribution of single variables and relationships between two variables.

We can see the realtionship between all the columns with each other in above chart.

1. From the above pair plot we can see that if cancellation increases then total stay also decreases.

2. As the total number of people increases adr also increases. Thus adr and total people are directly proportional to each other.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

1. Resort Hotel is most preffered so Stakeholders can offer discounts on City Hotel to increase bookings.

2. Around 27.52% of bookings are cancelled so Hotel can offer layality discount if guests don't cnacel their booking.

3. Hotel can maintain raw materials for BB type meal in advance to avoid delay as BB(Bead and Breakfast) is the most preffered meal.

4. Hotel should increase number of rooms in City Hotels to decrease the waiting time.

5. TA has the most number of bookings over other MArket segments so Hotel could run some offer to get more bookings from otehr segment.

6. Room type A is most preffered by guests so Hotel should increase the number of A type room.

7. Number of repeated guests is low that indicates that there is something they don't like about Hotel and that needs to be fixed to increase number of repeated guests.

8. Waiting time period for City hotel is high as compared to resort hotels. That means city hotels are much busier than Resort hotels.

9. Optimal stay in both the type hotel is less than 7 days. Usually people stay for a week so Hotel need to take some actions to improve their performance.

10. Maximum number of guests were from Portugal.

# **Conclusion**

Inorder to achieve the business objective, i would suggest the client to make the price dynamic, introduce offers and packages to attract new customers. To retain the existing customers and ensure their repetition the client must introduce loyalty points program which can be redeemed by the customers in their next bookings. Amenities such as parking spaces, kids corner, free internet connection can be provided to increase the number of bookings.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""